### ISSUE TITLE
Gamepad Controls Are Broken in Various Ways

### ISSUE THREAD

**Issue by zicklag** [fishfolks/punchy#213]
### Description

Right now, pressing down on the stick moves you up a button on the menu, and no movement works during the game.

Need to investigate, and this should definitely block the release.

**Comment by zicklag** [comment]
Fixed in https://github.com/Leafwing-Studios/leafwing-input-manager/pull/232.

If we need to we can switch to a git dependency real quick to get a fix for the next Punchy release, but I think a bugfix release will be made soon enough, and probably before we need to release punchy so I'll wait first.

**Comment by erlend-sh** [comment]
@alice-i-cecile do you suggest we switch to git dependency for now? I’m quite certain we’ll do a release within the next week.

**Comment by alice-i-cecile** [comment]
@zicklag @erlend-sh I'm on vacation but if you prepare a point release for LWIM in that PR I'll merge it and then publish it for you :)

**Comment by odecay** [comment]
This should be closed by #237 correct?
