### ISSUE TITLE
Melee Weapons

### ISSUE THREAD

**Issue by zicklag** [fishfolks/punchy#86]
Melee weapons are items which while held change the fighters available attacks.

My proposed design for this would be to move available attacks to a component with a hashmap/vec of attacks which is attached to each player.
Items with attacks should have their attacks added to `AvailableAttacks` component of the fighter they are picked up by while held, with the ability to take priority over the fighters innate attacks (dependent on design of weapon).

For non weapon items, we could decide to either block the fighter from using a subset of their attacks while holding them, through the same method or default to "the only attack you can do while holding a non weapon item is to throw the item, freeing up your hands to continue attacking."

This also calls into question whether all items should be required to have an attack, and/or if we should change the damage field in item definitions to be throw damage instead (since damage stat in fighters has now moved to being attack specific)
This also raises the question of how best to represent the animations of weapon attacks, since they will implicate both the fighters spritesheet and weapon spritesheet.

**Comment by Zac8668** [comment]
I'll claim this
